-- MySQL Script generated by MySQL Workbench
-- 05/20/17 13:29:46
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema epmprojbank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epmprojbank` DEFAULT CHARACTER SET cp1251 ;
USE `epmprojbank` ;

-- -----------------------------------------------------
-- Table `epmprojbank`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epmprojbank`.`clients` ;

CREATE TABLE IF NOT EXISTS `epmprojbank`.`clients` (
  `name` VARCHAR(42) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(32) NULL DEFAULT NULL,
  `role` BIGINT(20) NULL DEFAULT NULL,
  `id_client` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
;


-- -----------------------------------------------------
-- Table `epmprojbank`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epmprojbank`.`accounts` ;

CREATE TABLE IF NOT EXISTS `epmprojbank`.`accounts` (
  `id_account` INT(11) NOT NULL AUTO_INCREMENT,
  `number` BIGINT(20) NULL DEFAULT NULL,
  `clients_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_account`, `clients_id`),
  INDEX `fk_accounts_clients1_idx` (`clients_id` ASC),
  CONSTRAINT `fk_accounts_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `epmprojbank`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
;


-- -----------------------------------------------------
-- Table `epmprojbank`.`fees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epmprojbank`.`fees` ;

CREATE TABLE IF NOT EXISTS `epmprojbank`.`fees` (
  `id_fee` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `trans_fee` DOUBLE NULL DEFAULT NULL,
  `newcard_fee` DOUBLE NULL DEFAULT NULL,
  `apr` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_fee`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
;


-- -----------------------------------------------------
-- Table `epmprojbank`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epmprojbank`.`cards` ;

CREATE TABLE IF NOT EXISTS `epmprojbank`.`cards` (
  `id_card` INT(11) NOT NULL AUTO_INCREMENT,
  `number` DECIMAL(16,0) NULL DEFAULT NULL,
  `exp_date` DATE NULL DEFAULT NULL,
  `fees_id` INT(11) NOT NULL,
  `accounts_id_account` INT(11) NOT NULL,
  PRIMARY KEY (`id_card`, `fees_id`, `accounts_id_account`),
  INDEX `fk_cards_fees1_idx` (`fees_id` ASC),
  INDEX `fk_cards_accounts1_idx` (`accounts_id_account` ASC),
  CONSTRAINT `fk_cards_fees1`
    FOREIGN KEY (`fees_id`)
    REFERENCES `epmprojbank`.`fees` (`id_fee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_accounts1`
    FOREIGN KEY (`accounts_id_account`)
    REFERENCES `epmprojbank`.`accounts` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
;


-- -----------------------------------------------------
-- Table `epmprojbank`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epmprojbank`.`transactions` ;

CREATE TABLE IF NOT EXISTS `epmprojbank`.`transactions` (
  `id_trans` INT(11) NOT NULL AUTO_INCREMENT,
  `cr_account` BIGINT(20) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `accounts_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_trans`, `accounts_id`),
  INDEX `fk_transactions_accounts1_idx` (`accounts_id` ASC),
  CONSTRAINT `fk_transactions_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `epmprojbank`.`accounts` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
