INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (5, '0781-10-28', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (9, '0178-10-12', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (2, '0473-12-29', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (6, '1025-11-23', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (8, '0001-01-01', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (1, '1240-02-10', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (3, '1682-05-14', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (4, '1491-07-28', 0, 0);
INSERT INTO epmprojbank.cards (number, exp_date, fees_id, accounts_id_account) VALUES (7, '0631-10-27', 0, 0);